sudo: required

services:
  - docker

before_install:
  - docker version
  - sudo apt-get -y install python-pip
  - sudo pip install docker==2.7.0 docker-squash
  - docker build -t nanobox/bridge .

script: sudo test/run_all.sh

after_success:
  - export BRANCH=$(if [ "$TRAVIS_PULL_REQUEST" == "false" ]; then echo $TRAVIS_BRANCH; else echo $TRAVIS_PULL_REQUEST_BRANCH; fi)
  - docker login -u="$DOCKER_USERNAME" -p="$DOCKER_PASSWORD";
  - docker build -t ${NAMESPACE}/bridge .
  - docker-squash -t ${NAMESPACE}/bridge:squashed -f nanobox/runit --tmp-dir /var/tmp/squasher ${NAMESPACE}/bridge
  - docker tag ${NAMESPACE}/bridge:squashed ${NAMESPACE}/bridge:beta;
  - docker push ${REMOTE}${NAMESPACE}/bridge:beta;
  - if [ "$BRANCH" == "master" ]; then
    docker tag ${NAMESPACE}/bridge:squashed ${NAMESPACE}/bridge;
    docker push ${REMOTE}${NAMESPACE}/bridge;
    else
    docker tag ${NAMESPACE}/bridge:squashed ${NAMESPACE}/bridge:${BRANCH//\//_};
    docker push ${REMOTE}${NAMESPACE}/bridge:${BRANCH//\//_};
    fi
